### PR TITLE
[Translation] Brazilian Portuguese (pt-BR) - updated

### PR DESCRIPTION
**Pull request by eduardopato41**

### CODE REVIEW

**Comment by Haxxer** [comment]
Thank you for your contribution! I'll include this in the next update :)

**Comment by Haxxer** [comment]
@eduardopato41 I've changed how the heavy armor rest mechanic works, so that it functions on medium armor too. Would you mind translating these? :)

```json
"ExhaustionArmor": "They chose to keep their armor on, and recovered none of their exhaustion.",
"HitDiceArmor": "They recovered less hit dice than normal because they rested in their armor.",
"NoHitDiceArmor": "They recovered none of their hit dice because they rested in their armor.",
"HitDiceNoArmor": "They chose to not rest in their armor, and regained the normal amount of hit dice."


"AutomateArmor": {
  "Title": "Armor long rest automation",
  "Hint": "With this enabled, non-light armor impedes long rests. Configure below how it impacts the long rest."
},
"ArmorHitDiceRecoveryFraction": {
  "Title": "Armor hit dice recovery fraction",
  "Hint": "If the character is wearing non-light armor during the long rest, this is fraction of hit dice they recover on a long rest."
},
"AutomateArmorExhaustion": {
  "Title": "Armor prevents exhaustion recovery",
  "Hint": "When enabled and the character is wearing non-light armor during the long rest, they do not recover from exhaustion. Requires exhaustion automation to be enabled."
}
```

**Comment by eduardopato41** [comment]
If I'm not mistaken, this PR already had these strings translated (I updated after noticing the armor update). But I revised and updated some of the text. Want me to create a new PR?

```json
"ExhaustionArmor": "Ele(a) decidiu continuar vestindo sua armadura pesada, e não recuperou nenhum dos seus pontos de exaustão.",
"HitDiceArmor": "Ele(a) recuperou menos dados de vida que o normal porque descansou vestindo sua armadura pesada.",
"NoHitDiceArmor": "Ele(a) não recuperou nenhum dado de vida porque descansou vestindo sua armadura pesada.",
"HitDiceNoArmor": "Ele(a) decidiu não vestir a sua armadura pesada enquanto descansa e recuperou a quantidade normal de dados de vida."

"AutomateArmor": {
  "Title": "Automação de descanso longo com armadura",
  "Hint": "Com esta opção habilitada, armaduras que não sejam leve dificultam descansos longos. Configure abaixo como isso afeta o descanso longo."
},
"ArmorHitDiceRecoveryFraction": {
  "Title": "Fração de recuperação de dados de vida com armadura",
  "Hint": "Se o personagem estiver usando uma armadura que não seja leve durante um descanso longo, esta é a fração dos dados de vida que ele recupera em um descanso longo."
},
"AutomateArmorExhaustion": {
  "Title": "Armadura impede recuperação de exaustão",
  "Hint": "Quando habilitada e o personagem estiver usando uma armadura que não seja leve durante um descanso longo, ele não recupera nenhum ponto de exaustão. Requer que a automação de exaustão esteja habilitada."
}
```

**Comment by Haxxer** [comment]
You're right, they were! But the original strings specifically mentioned only heavy armor, but according to a new request the optional rule also affects medium armor, which is why I reached out :)

**Comment by Haxxer** [comment]
You didn't miss anything, I just changed the English version a bit.

**Comment by eduardopato41** [comment]
You're right! Didn't even noticed haha
I revised the options but not the chat messages. Now I edited them too.
Thanks!

**Pull request merged**
